$zbiory = ['Miejscowe Plany Zagospodarowania Przestrzennego',
    'Nagrania Posiedzeń Rady Dzielnicy',
    'Karty Parkingowe dla niepełnosprawnych wg. adresów',
    'Zgłoszenia na warszawski numer 19115',
    'Rozkład jazdy komunikacji publicznej',
    'Rejestr umów Urzędu Miasta',
    'Zabytkowe Pomniki Nagrobne',
    'Wysokość i ilość świadczeń społecznych',
    'Prowadzone projekty unijne',
    'Diety radnych miasta',
    'Urodzenia, małżeństwa, zgony',
    'Zarejestrowane zwierzęta domowe (gatunek, lokalizacja)',
    'Ośrodki szkolenia kierowców',
    'Naruszenia dyscypliny finansów publicznych przez osoby pełniące funkcje publiczne',
    'Skargi i wnioski składane do Urzędu Miasta',
    'Złożone wnioski o Informację Publiczną',
    'Wydarzenia kulturalne, miejsca związane z kulturą i twórcy kultury',
    'Roczne sprawozdania finansowe',
    'Zezwolenia Alkoholowe (wnioski, decyzje, limity)',
    'Inwestycje realizowane w pasie drogowym',
    'Sprawy sądowe prowadzone przez miasto',
    'Mapa hałasu - wskaźniki i tereny wrażliwe',
    'Zamówienia publiczne do wartości 30 tysięcy Euro',
    'Używane oprogramowanie',
    'Prowadzone zajęcia szkolne',
    'Sprzęt komputerowy',
    'Adresy (adres, działka, kod)',
    'Ulice, place, ronda, skwery',
    'Pozwolenia na wprowadzanie pyłów do powietrza',
    'Instytucje kultury',
    'Radni miasta: uchwały, interpelacje i zapytania radnych',
    'Zarządzenia władz miasta',
    'Wykonane przelewy bankowe',
    'Wysokości zadłużeń alimentacyjnych',
    'Honorowi obywatele miasta',
    'Zarejestrowane pojazdy',
    'Nagrody przyznane przez miasto',
    'Uchwały Rady Miasta',
    'Tereny objęte ochroną przyrody',
    'Stanowiska przyjęte przez Radę Miasta',
    'Faktury VAT - zakupy i sprzedaż',
    'Przyznane kary za ścięte drzewa',
    'Opłaty roczne za wieczyste użytkowanie gruntów',
    'Jednostki oświatowe - dane założycielskie, dyrektorzy, informacje kontaktowe',
    'Miejskie nieruchomości na sprzedaż',
    'Gminna Ewidencja Zabytków',
    'Niepubliczne jednostki oświatowe',
    'Zaplanowane zamówienia publiczne',
    'Wykonawcy, z którymi rozwiązano umowy',
    'Lista nieruchomości zwróconych właścicielom lub następcom prawnym właścicieli w związku z obowiązywaniem "dekretu Bieruta"',
    'Dotacje przyznane organizacjom pozarządowym na finansowanie wypoczynku zorganizowanego dla dzieci i młodzieży w okresie ferii letnich i zimowych',
    'Księgozbiór bibliotek',
    'Biblioteki - Katalog filmów, audiobooków i płyt muzycznych',
    'Sklepy alkoholowe',
    'Miejsca dopuszczone do prowadzenia handlu obwoźnego',
    'Hotele, hostele, itp.',
    'Umowy dzierżawy',
    'Członkowie organów gminy, referenda, grunty komunalne',
    'Lista lokali socjalnych',
    'Ścieżki rowerowe, buspasy, dworce i inna infrastruktura',
    'Członkowie Zarządu i Rady Dzielnicy',
    'Uchwały Zarządu Dzielnicy Wola',
    'Ocena ryzyka prowadzonych projektów miejskich',
    'Oświadczenia majątkowe radnych miasta',
    'Baza danych placówek oświatowych',
    'Ewidencja pustostanów',
    'Ewidencja lokali socjalnych',
    'Miejsca pamięci',
    'Stowarzyszenia nadzorowane przez miasto',
    'Pozwolenia na zbiórki publiczne',
    'Baza zbiorów bibliotecznych',
    'Spis ksiąg parafialnych z lat 1910-2009',
    'Najpopularniejsze imiona dziewcząt i chłopców wg. lat',
    'Miejskie place zabaw',
    'Placówki udzielające pomocy w sytuacji przemocy w rodzinie',
    'Wykaz pomników, fontann i zdroi administrowanych przez miasto',
    'Targowiska stałe na terenie miasta',
    'Planowanie strategiczne - Projekty umów, decyzji, spraw na zarząd',
    'System Zliczania Pasażerów Komunikacji Miejskiej',
    'Ogłoszenia o naborach na wolne stanowiska urzędnicze',
    'Obwody szkolne',
    'Demografia miasta: narodziny, zgony, migracje zewnętrzne i międzydzielnicowe',
    'Rejestr wniosków i wydanych decyzji o warunkach zabudowy',
    'Programy i projekty finansowane ze środków UE',
    'Miejskie Kluby Sportowe',
    'Zima w mieście, Lato w mieście - zajęcia, organizatorzy, liczba uczestników',
    'Notyfikacje PUSH dot. czasowych zakazów parkowania (np. wizyty zagranicznych gości)',
    'Projekty realizowane przez dzielnice - nazwa, opis, terminy, kwota',
    'Wykaz osób uprawnionych do dostępu do informacji niejawnych',
    'Rejestr karmicieli kotów dzikich - miejsca oraz ilość dokarmianych kotów',
    'Przyznane dotacje dla podmiotów wyłonionych w otwartych konkursach ofert',
    'Ceny gruntów',
    'Wykaz miejskich kin, teatrów, muzeów, galerii',
    'Dane statystyczne z systemów kolejkowych w odziałach UM - czas obsługi, czas czekania, ilość oczekujących osób',
    'Rejestr szkół i placówek niepublicznych',
    'Uczniowie niepełnosprawni dowożeni do szkół',
    'Rejestr sprzedanych lokali komunalnych',
    'Decyzje ustalajace dopuszczalny poziom hałasu',
    'Decyzje zezwalajace na usunięcie drzew lub krzewów',
    'Rejestr wysłanych zawiadomień do prokuratury',
    'Punkty dostępowe miejskiego WiFi',
    'Lokalizacje stacji rowerów miejskich i ilość wolnych rowerów',
    'Wypożyczenia rowerów miejskich',
    'Bieżące położenie GPS pojazdów komunikacji miejskiej',
    'Szyny tramwajowe - sieć miejska',
    'Zieleń miejska - drzewa, krzewy, kwietniki, trawniki, jeziorka...',
    'Realizacja rozkładu jazdy komunikacji publicznej',
    'Inwestycje wodociągowe i kanalizacyjne',
    'Ewidencja ludności',
    'Ogłoszenia o zamówieniach publicznych',
    'Gospodarka leśna',
    'Odholowania samochodów',
    'Mandaty wystawione przez straż miejską',
    'Dane z systemu parkometrów',
    'Ceny nieruchomości',
    'Interwencje Straży Miejskiej',
    'Zdarzenia niebezpieczne z udziałem rowerzystów',
    'Patrole szkolne - interwencje w szkołach i okolicach szkół',
    'Dane z fotoradarów SM',
    'Dane lokalizacyjne patroli SM',
    'Budżet - wydatki i dochody',
    'Taksówki MPT',
    'Ewidencja rzeczy znalezionych',
    'Inwestycje drogowe',
    'Biletomaty - natężenie ruchu, itp.',
    'Przejścia przez bramki metra',
    'Miejsca składowania odpadów, dzikich wysypisk',
    'Lokalizacja psów ras uznanych za agresywne',
    'Infrastruktura sportowa - dostępność, oferta',
    'Prowadzone konsultacje społeczne',
    'Realizacja i przebieg budżetu obywatelskiego',
    'Natężenie ruchu ulicznego',
    'Wypadki i kolizje na drodze',
    'Synchronizacja i funkcjonowanie sygnalizacji świetlnej',
    'Działalność Miejskiego Transportu Osób Niepełnosprawnych',
    'Osiedla i obszary grodzone',
    'Zaczipowane kosze na śmieci',
];

target = [
    'młodzież przedszkolna',
    'młodzieży szkolna',
    'studenci',
    'osoby pracujące',
    'osoby 60+',
    'kobiety',
    'mężczyźni',
    'dzieci',
    'uczniowie',
    'pracownicy fizyczni',
    'wykładowcy uczelni wyższych',
    'informatycy',
    'politycy',
    'miejscy aktywiści'
];